### ISSUE TITLE
Find a Better WordPress Theme

### ISSUE THREAD

**Issue by eljobe** [wmwnc/website#7]
Currently, https://womensmarchwnc.com/ uses the [Dyad](https://wordpress.org/themes/dyad/) theme.

Browse around the [WordPress Theme repository](https://wordpress.org/themes/) and see if you can find one that is closer to what you like for the website.

If you're feeling brave, you can even change the theme on the live (but not yet publically announced) site by following [these instructions](https://codex.wordpress.org/Using_Themes#Adding_New_Themes_using_the_Administration_Panels). However, if you have any concerns about switching themes, I'm happy to do it.

Also, remember that the theme you choose is really just a starting point. We can definitely tweak them later to get the "perfect" font, or change the width or positions of elements in the theme. So, don't feel like you have to find one you're totally satisfied with.

**Comment by eljobe** [comment]
Looking to see if you've made any progress on finding a theme you like more. Or, short of that a font you'd be really satisfied with on the site. I could see what it would take to get the font from the current site and use it on the new site, but I'm hesitant to make appearance tweaks to this theme before we've sorted out whether or not it is the theme we want for the site.

**Comment by mgermain99** [comment]
Hi Pepper:

I can't seem to find the email with the log in info. Can you resend?

Thanks, Marie

________________________________

**Comment by eljobe** [comment]
We decided to stick with the current theme. I've opened several new issues to track the progress of tweaking that theme to work for the website. This card can be closed since we know we're sticking with Dyad for now and just trying to tweak it to make it what we want it to be.
